### ISSUE TITLE
--opt option collapsed.

### ISSUE THREAD

**Issue by sisshiki1969** [mame/optcarrot#37]
It seems that --opt option came to raise error after the commit 47e0c7c3986ba310f49fb70dc9fa69ef37a1f631.

```sh
$ bin/optcarrot-bench
fps: 40.6957710763183
$ bin/optcarrot-bench --opt
fps: 130.21812983686382
/home/optcarrot/lib/optcarrot/ppu.rb:894:in `dispose': undefined method `resume' for nil:NilClass (NoMethodError)
        from /home/monochrome/optcarrot/lib/optcarrot/nes.rb:77:in `dispose'
        from /home/monochrome/optcarrot/lib/optcarrot/nes.rb:96:in `run'
        from bin/optcarrot-bench:9:in `<main>'
```

**Comment by sisshiki1969** [comment]
I created a PR. #38 to fix it.

After PR:

```sh
$ bin/optcarrot-bench
fps: 41.443371316954384
$ bin/optcarrot-bench --opt
fps: 129.3614574714836
```
